language: php
php:
  - "5.4"
  - "5.3"
branches_only:
  - master
before_script:
  - sudo apt-get update 
  - sudo apt-get install apache2 libapache2-mod-php5 php5-curl php5-mysql
  - sudo a2enmod rewrite;
  - echo "$(curl -fsSL https://raw.github.com/gist/3813442/ef670806255fdd2a21b0f3f80d863035f0b4b112/gistfile1.txt)" | sed -e "s,PATH,`pwd`/app,g" | sudo tee /etc/apache2/sites-available/default
  - echo "FallBackResource ./index.php" > app/.htaccess
  - mysql -e 'create database usarugby'
  - mysql -u root usarugby < db/schema.sql
  - mysql -u root usarugby < db/data.sql
  - mv behat.yml.dist behat.yml
  - echo "$(curl -fsSL https://raw.github.com/gist/3814376/a4ba9ea9f57ee8c2abb5b8a08ad843c453d4132c/config.php)" | sudo tee app/config.php
  - composer install --dev
  - sudo service apache2 restart
script:
  - bin/behat --verbose
