language: php
php:
  - "5.4"
  - "5.3"
before_script:
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-php5 php5-curl php5-mysql
  - sudo a2enmod rewrite;
  - echo "$(cat .travisci/apache2.txt)" | sed -e "s,PATH,`pwd`/app,g" | sudo tee /etc/apache2/sites-available/default
  - echo "FallBackResource ./index.php" > app/.htaccess
  - mysql -e 'create database usarugby'
  - mysql -u root usarugby < db/schema.sql
  - mysql -u root usarugby < db/data.sql
  - mv behat.yml.dist behat.yml
  - echo "$(cat .travisci/config.php)" | sudo tee app/config.php
  - composer install -n --dev
  - sudo service apache2 restart
  - curl -vvv http://localhost
script:
  - bin/behat --verbose
